apiVersion: v1
kind: Service
metadata:
  name: esp-grpc-challenge
spec:
  ports:
    # Port that accepts gRPC and JSON/HTTP2 requests over HTTP.
    - port: 80
      targetPort: 9000
      protocol: TCP
      name: http2
  selector:
    app: esp-grpc-challenge
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: esp-grpc-challenge-json
spec:
  ports:
    # Port that accepts gRPC and JSON/HTTP2 requests over HTTP.
    - port: 80
      targetPort: 9001
      protocol: TCP
      name: http
  selector:
    app: esp-grpc-challenge
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esp-grpc-challenge
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: esp-grpc-challenge
    spec:
      containers:
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:1.16.0
          args: [
            "--http_port=9001",
            "--http2_port=9000",
            "--service=challenge-grpc.endpoints.challenge-api.cloud.goog",
            "--rollout_strategy=managed",
            "--backend=grpc://127.0.0.1:8080",
            "--cors_preset=basic"
          ]
          ports:
            - containerPort: 9000
        - name: challenge
          image: skyfrog28/challenge:1.14
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_IP
              value: 10.39.32.3
