// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Challenge.proto

package challenge

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateSkillRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSkillRequest) Reset()         { *m = CreateSkillRequest{} }
func (m *CreateSkillRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSkillRequest) ProtoMessage()    {}
func (*CreateSkillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13823e0ab8b4620, []int{0}
}

func (m *CreateSkillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSkillRequest.Unmarshal(m, b)
}
func (m *CreateSkillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSkillRequest.Marshal(b, m, deterministic)
}
func (m *CreateSkillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSkillRequest.Merge(m, src)
}
func (m *CreateSkillRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSkillRequest.Size(m)
}
func (m *CreateSkillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSkillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSkillRequest proto.InternalMessageInfo

func (m *CreateSkillRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Skills struct {
	Skills               []*Skill `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Skills) Reset()         { *m = Skills{} }
func (m *Skills) String() string { return proto.CompactTextString(m) }
func (*Skills) ProtoMessage()    {}
func (*Skills) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13823e0ab8b4620, []int{1}
}

func (m *Skills) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Skills.Unmarshal(m, b)
}
func (m *Skills) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Skills.Marshal(b, m, deterministic)
}
func (m *Skills) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Skills.Merge(m, src)
}
func (m *Skills) XXX_Size() int {
	return xxx_messageInfo_Skills.Size(m)
}
func (m *Skills) XXX_DiscardUnknown() {
	xxx_messageInfo_Skills.DiscardUnknown(m)
}

var xxx_messageInfo_Skills proto.InternalMessageInfo

func (m *Skills) GetSkills() []*Skill {
	if m != nil {
		return m.Skills
	}
	return nil
}

type Skill struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Skill) Reset()         { *m = Skill{} }
func (m *Skill) String() string { return proto.CompactTextString(m) }
func (*Skill) ProtoMessage()    {}
func (*Skill) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13823e0ab8b4620, []int{2}
}

func (m *Skill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Skill.Unmarshal(m, b)
}
func (m *Skill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Skill.Marshal(b, m, deterministic)
}
func (m *Skill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Skill.Merge(m, src)
}
func (m *Skill) XXX_Size() int {
	return xxx_messageInfo_Skill.Size(m)
}
func (m *Skill) XXX_DiscardUnknown() {
	xxx_messageInfo_Skill.DiscardUnknown(m)
}

var xxx_messageInfo_Skill proto.InternalMessageInfo

func (m *Skill) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Skill) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_d13823e0ab8b4620, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateSkillRequest)(nil), "challenge.CreateSkillRequest")
	proto.RegisterType((*Skills)(nil), "challenge.Skills")
	proto.RegisterType((*Skill)(nil), "challenge.Skill")
	proto.RegisterType((*Empty)(nil), "challenge.Empty")
}

func init() { proto.RegisterFile("Challenge.proto", fileDescriptor_d13823e0ab8b4620) }

var fileDescriptor_d13823e0ab8b4620 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x77, 0xce, 0x48, 0xcc,
	0xc9, 0x49, 0xcd, 0x4b, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4c, 0x86, 0x09,
	0x48, 0xc9, 0xa4, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x27, 0x16, 0x64, 0xea, 0x27, 0xe6, 0xe5,
	0xe5, 0x97, 0x24, 0x96, 0x64, 0xe6, 0xe7, 0x15, 0x43, 0x14, 0x2a, 0x69, 0x70, 0x09, 0x39, 0x17,
	0xa5, 0x26, 0x96, 0xa4, 0x06, 0x67, 0x67, 0xe6, 0xe4, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97,
	0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81,
	0xd9, 0x4a, 0x46, 0x5c, 0x6c, 0x60, 0x35, 0xc5, 0x42, 0x1a, 0x5c, 0x6c, 0xc5, 0x60, 0x96, 0x04,
	0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0x80, 0x1e, 0xdc, 0x36, 0x3d, 0x88, 0x31, 0x50, 0x79, 0x25,
	0x6d, 0x2e, 0x56, 0xb0, 0x80, 0x10, 0x1f, 0x17, 0x53, 0x66, 0x0a, 0xd8, 0x38, 0xd6, 0x20, 0xa6,
	0xcc, 0x14, 0xb8, 0x05, 0x4c, 0x48, 0x16, 0xb0, 0x73, 0xb1, 0xba, 0xe6, 0x16, 0x94, 0x54, 0x1a,
	0x2d, 0x61, 0xe4, 0xe2, 0x84, 0x7b, 0x48, 0x28, 0x90, 0x8b, 0x1b, 0xc9, 0x85, 0x42, 0xb2, 0x48,
	0x96, 0x61, 0xba, 0x5c, 0x0a, 0xc3, 0x2d, 0x4a, 0x82, 0x4d, 0x97, 0x9f, 0x4c, 0x66, 0xe2, 0x56,
	0xe2, 0xd4, 0x2f, 0x33, 0xd4, 0x07, 0xbb, 0x4b, 0xc8, 0x85, 0x8b, 0xcb, 0x27, 0xb3, 0xb8, 0x04,
	0xea, 0x1d, 0x64, 0x2d, 0x60, 0x07, 0x48, 0x09, 0xa2, 0x1b, 0x52, 0x0c, 0x33, 0x45, 0x08, 0x61,
	0x4a, 0x12, 0x1b, 0x38, 0x04, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8d, 0xda, 0x38, 0x4b,
	0x7d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChallengeClient is the client API for Challenge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChallengeClient interface {
	CreateSkill(ctx context.Context, in *CreateSkillRequest, opts ...grpc.CallOption) (*Skill, error)
	ListSkills(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Skills, error)
}

type challengeClient struct {
	cc *grpc.ClientConn
}

func NewChallengeClient(cc *grpc.ClientConn) ChallengeClient {
	return &challengeClient{cc}
}

func (c *challengeClient) CreateSkill(ctx context.Context, in *CreateSkillRequest, opts ...grpc.CallOption) (*Skill, error) {
	out := new(Skill)
	err := c.cc.Invoke(ctx, "/challenge.Challenge/CreateSkill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *challengeClient) ListSkills(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Skills, error) {
	out := new(Skills)
	err := c.cc.Invoke(ctx, "/challenge.Challenge/ListSkills", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChallengeServer is the server API for Challenge service.
type ChallengeServer interface {
	CreateSkill(context.Context, *CreateSkillRequest) (*Skill, error)
	ListSkills(context.Context, *Empty) (*Skills, error)
}

func RegisterChallengeServer(s *grpc.Server, srv ChallengeServer) {
	s.RegisterService(&_Challenge_serviceDesc, srv)
}

func _Challenge_CreateSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChallengeServer).CreateSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/challenge.Challenge/CreateSkill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChallengeServer).CreateSkill(ctx, req.(*CreateSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Challenge_ListSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChallengeServer).ListSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/challenge.Challenge/ListSkills",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChallengeServer).ListSkills(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Challenge_serviceDesc = grpc.ServiceDesc{
	ServiceName: "challenge.Challenge",
	HandlerType: (*ChallengeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSkill",
			Handler:    _Challenge_CreateSkill_Handler,
		},
		{
			MethodName: "ListSkills",
			Handler:    _Challenge_ListSkills_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Challenge.proto",
}
